spring:
  datasource:
    url: jdbc:postgresql://35.192.106.73:5432/servicampo_db  # Replace with your PostgreSQL URL
    driver-class-name: org.postgresql.Driver
    username: servi  # Replace with your PostgreSQL username
    password: JG4n0Lvn0$Zfp2Zf  # Replace with your PostgreSQL password
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none # Important: Use a proper DDL strategy for production! (e.g., validate, update)
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  cloud:
    gcp:
      enabled: true # Enable GCP Storage auto-configuration
      project-id: servicampo-dev
      credentials:
        location: classpath:credentials.json # Path to your service account JSON file

#    azure:
#      storage:
#        account-name: your-azure-storage-account-name # Replace with your Azure Storage account name
#        account-key: your-azure-storage-account-key # Replace with your Azure Storage account key
#cloud:
#  aws:
#    region: your-aws-region # Replace with your AWS region (e.g., us-east-1)
#    credentials:
#      access-key: your-access-key # Replace with your AWS access key ID
#      secret-key: your-secret-access-key # Replace with your AWS secret access key

file:
  storage:
    platform: gcp # Set to gcp, aws, azure, or local
    buckets:
      main: servicampo-bucket-dev
    folders:
      imagenes: Imagenes
      imagenes.clientes: Clientes
      imagenes.empleados: Empleados
      imagenes.productos: Productos
      evidencias: Evidencias
      evidencias.imagenes: imagenes
      evidencias.audios: audio

mybatis:
  schema: dev_v2

jwt:
  secret: QUw0Pga3sWOcRrr8Cqnm4GTMxyxK5fyBYI7qgGFB8FV+iHHMY+lK/8CPAfe6G7cOjtOtsvQLb0Om12vvq/4bBg==
  expiration: 86400000 # Example: 1 day (in milliseconds)

server:
  servlet:
    context-path: /api/v1

  port: 8080